name: eux-journal
ingress: https://eux-journal.intern.nav.no

database:
  name: eux-journal-db
  tier: db-custom-1-3840

application:
  eux-neessi:
    name: eux-neessi
    namespace: eessibasis

  eux-fagmodul-journalfoering:
    name: eux-fagmodul-journalfoering
    namespace: eessibasis

  eux-oppgave:
    name: eux-oppgave
    namespace: eessibasis

  eux-nav-rinasak:
    name: eux-nav-rinasak
    namespace: eessibasis

client:
  euxnavrinasak:
    url: http://eux-nav-rinasak
    scope: api://prod-gcp.eessibasis.eux-nav-rinasak/.default

  euxoppgave:
    endpoint: http://eux-oppgave
    scope: api://dev-gcp.eessibasis.eux-oppgave/.default

  saf:
    host: saf.prod-fss-pub.nais.io
    url: https://saf.prod-fss-pub.nais.io
    scope: api://prod-fss.teamdokumenthandtering.saf/.default

  dokarkiv:
    host: dokarkiv.prod-fss-pub.nais.io
    url: https://dokarkiv.prod-fss-pub.nais.io
    scope: api://prod-fss.teamdokumenthandtering.dokarkiv/.default

cluster:
  fss: prod-fss
  gcp: prod-gcp
