name: eux-journal
ingress: https://eux-journal.intern.nav.no

database:
  name: eux-journal-db
  tier: db-custom-1-3840

application:
  eux-neessi:
    name: eux-neessi
    namespace: eessibasis
  eux-fagmodul-journalfoering:
    name: eux-fagmodul-journalfoering
    namespace: eessibasis

client:
  oppgave:
    endpoint: https://oppgave.prod-fss-pub.nais.io
    scope: api://prod-fss.oppgavehandtering.oppgave/.default

cluster:
  fss: prod-fss
  gcp: prod-gcp
