openapi: 3.0.3
info:
  title: Eux Journal API
  description: API til bruk av EUX apper for 책 h책ndtere NAV Oppgaver
  contact:
    name: vegard.lundeberg.hillestad@nav.no
  version: v1
servers:
  - url: 'http://localhost:8080/api/v1'
tags:
  - name: Eux Journal API
    description: >-
      API til bruk av EUX apper for 책 h책ndtere NAV Oppgaver

paths:
  '/rinasaker/{rinasakId}/journalposter/feilregistrer':
    $ref: 'feilregistrer/operations_rot.yaml'
  '/journalposter/settStatusAvbryt':
    $ref: 'journalposter/operations_rot.yaml'
  '/journalposter/{journalpostId}/ferdigstill':
    $ref: 'ferdigstill/operations_rot.yaml'
