openapi: 3.0.3
info:
  title: Eux Journal API
  description: API til bruk av EUX apper for å håndtere Nav journalpost
  contact:
    name: vegard.lundeberg.hillestad@nav.no
  version: v1
servers:
  - url: '/'
tags:
  - name: Journalposter
    description: >-
      API til bruk av EUX apper for å håndtere Nav Journalposter
  - name: Rinasaker
    description: >-
      API til bruk av EUX apper for å håndtere Nav Journalposter

paths:
  '/api/v1/rinasaker/{rinasakId}/journalposter/feilregistrer':
    $ref: 'feilregistrer/operations_rot.yaml'
  '/api/v1/journalposter/settStatusAvbryt':
    $ref: 'journalposter/operations_rot.yaml'
  '/api/v1/journalposter/{journalpostId}/ferdigstill':
    $ref: 'ferdigstill/operations_rot.yaml'
